name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main
      - newsite  # or whatever your subdomain branch is called

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build Site
        run: |
          # replace this with your build command
          npm install
          npm run build

      - name: Add CNAME
        run: |
          DOMAIN=""
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            DOMAIN="hortonpaul.com"
          elif [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            DOMAIN="dev.hortonpaul.com"
          fi
          echo "$DOMAIN" > ./dist/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
